### ISSUE TITLE
Implement various distance functions

### ISSUE THREAD

**Issue by gsomix** [tsoding/voronoi-diagram#3]
It would be interesting to see visualization of Voronoi diagram with another distance function, e.g. Manhattan distance [1]. Alternatively you can generalize current distance with p-norm [2].

[1] https://en.wikipedia.org/wiki/Taxicab_geometry
[2] https://en.wikipedia.org/wiki/Norm_%28mathematics%29#p-norm

**Comment by rexim** [comment]
Yeah! I was thinking about that too! Thanks! Planned for the stream: https://trello.com/c/6NhfVcFi/117-implement-various-distance-functions-issue-3-tsoding-voronoi-diagram-github :)

**Comment by gsomix** [comment]
It was very interesting. Thanks again!
