### ISSUE TITLE
Implement space partitioning

### ISSUE THREAD

**Issue by gsomix** [tsoding/voronoi-diagram#6]
## Useful links
- https://en.wikipedia.org/wiki/K-d_tree
## Description

To speed up querying nearest site for each pixel we can introduce space partitioning, e.g. grid or binary tree. Of course it may be argued that the Voronoi diagram is space partitioning structure itself... But current implementation is, you know, just visualization.

**Comment by rexim** [comment]
Accepted. Thank you!
